# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "de-DE"
title                    : "Dominik Lenhardt IT-Services"
title_separator          : "|"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Dominik Lenhardt"
description              : "Beratung, Entwicklung, Betrieb von IT-Systemen und Azure Infrastruktur"
url                      : "https://onkeldom.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "OnkelDom/onkeldom.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           :  # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
comments:
  provider               : utterances # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : "onkeldom" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : "github-light" # "github-light" (default), "github-dark"
    issue_term           : "pathname" # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : "OnkelDominik"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links                  : # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Dominik Lenhardt"
  avatar           : "/assets/images/onkeldom_avatar.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Beratung, Entwicklung, Betrieb von IT-Systemen und Azure Infrastruktur"
  location         : "Babenhausen, DE"
  email            : "dominik@lenhardt.cc"
  twitter          : "OnkelDominik"
  xing             : "Dominik_Lenhardt"
  linkedin         : "dominik-lenhardt-086645226"
  github           : "OnkelDom"
  steam            : "" # onkeldom
  youtube          : "" # d3mka
  instagram        : "" #onkeldominik
  stackoverflow    : "17848024/dominik-lenhardt"
  links: {}
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://lenhardt.cc"

# Experiences
author_work_experiences_details:
  - logo: linux.png
    url: https://www.linux.org
    designation: Linux Systemadministrator
    description: |
      Vertraut mit RedHat und Ubuntu. Grundlegende Infrastruktur (DHCP, DNS, NTP), Proxyserver (Squid, Socks, PAC/WPAD), Loadbalancer (Keepalived, HAproxy, Traefik), Monitoring (Consul, Prometheus Stack), Hochverfügbarkeit und Sicherheit.
    visibility: true
  - logo: microsoft.png
    url: https://microsoft.com
    designation: Azure Cloud Administrator
    description: Architektur, Konzeptionierung, Betrieb, Automatisierte Deployments mit ARM, BICEP und PowerShell.
    visibility: true
  - logo: ansible.png
    url: https://www.ansible.com
    designation: Konfigurationsmangement
    description: Bereitstellen und pflegen von Rollen sowie verwaltung von Servern mittels Konfigurationsmanagement.
    visibility: true

# Education
author_education_details:
  - degree: "Fachinformatiker für Systemintegration"
    name: "ATLAS Dienstleistungen für Vermögensberatung GmbH"
    logo: fisi.jpg
    url: https://www.ausbildung.de/berufe/fachinformatiker-systemintegration
    description: "08/2014 bis 01/2017"
    visibility: true
  - degree: "Linux Grundlagenschulung"
    name: "B1-Systems GmbH"
    logo: b1systems.jpg
    url: https://www.b1-systems.de/
    description: "8/2014"
    visibility: true
  - degree: "ITIL Foundation"
    name: "ATLAS Dienstleistungen für Vermögensberatung GmbH"
    logo: itil.png
    url: https://www.itlibrary.org/
    description: "08/2018"
    visibility: true
  - degree: "Microsoft Azure Fundamentals (AZ-900)"
    name: "ATLAS Dienstleistungen für Vermögensberatung GmbH"
    logo: ms-az-900.png
    url: https://www.dvag.de
    description: "04/2019"
    visibility: true
  - degree: "Microsoft PowerShell Basics"
    name: "softwareONE"
    logo: powershell.png
    url: https://www.softwareone.com
    description: "08/2021 - Automating Administration With Windows PowerShell"
    visibility: true
  - degree: "Microsoft Azure Administrator (AZ-104T00)"
    name: "FastLane"
    logo: ms-az-104.png
    url: https://www.fastlane.net
    description: "11/2021"
    visibility: true

# Projects
author_project_details:
  - title: lenhardt.cc
    thumbnail: lenhardt.cc.jpg
    description: Meine persöhnliche Webseite gebaut mit Jekyll und gehostet als github page.
    url: https://lenhardt.cc
    visibility: true


# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/OnkelDominik" 
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/OnkelDom"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
  links_img:
    - label: "buymeacoffee"
      icon: "buymeacoffee.jpg"
      url: "https://www.buymeacoffee.com/OnkelDom"
    - label: "paypalme"
      icon: "paypalme.png"
      url: "https://www.paypal.me/Lenhardt1987"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Berlin" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author: Dominik Lenhardt
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      classes: wide
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide