backend:
  name: github
  repo: OnkelDom/onkeldom.github.io
  branch: master
  site_domain: onkeldom.github.com

media_folder: "/assets/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/images/posts" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow # To manage status (Edit, Draft, Publish)
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Author", name: "author", widget: "string", default: "onkeldom"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    folder: "_pages"
    create: true
    slug: ".md"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["single"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/<pagename>/"}
      - {label: "Author Profile", name: "author_profile", widget: "select", options: [true,false], default: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  # - name: "layouts"
  #   label: "Layouts"
  #   folder: "_layouts"
  #   extension: "html"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
  #     - {label: "Title", name: "title", widget: "string", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}