
name: 'Website Test'

on:
  workflow_dispatch:
  push:
    branches:
    - maaster

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: microsoft/playwright-github-action@v1
      - name: Install playwright
        run: npm i -D @playwright/test
      - name: Install playwright browsers
        run: npx playwright install
      - name: Run Test WebKit
        run: npx playwright test tests/lenhardt.cc.spec.mjs --project=webkit
      - name: Run Test Firefox
        run: npx playwright test tests/lenhardt.cc.spec.mjs --project=firefox
      - name: Run Test Chromium
        run: npx playwright test tests/lenhardt.cc.spec.mjs --project=chromium