
name: 'Website Test'

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and run tests
        run: npm install && npm playwright test tests/playwright_test.mjs
