
name: 'Website Test'

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - name: Install playwright
        run: npm i -D @playwright/test
      - name: Install playwright browsers
        run: npx playwright install
      - name: Run Test
        run: npx playwright test tests/playwright_test.mjs
